# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{good_touch}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Ryan Sonnek}]
  s.date = %q{2011-08-11}
  s.description = %q{ Update your timestamp attributes without invoking all ActiveRecord callbacks}
  s.email = %q{ryan@codecrate.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "good_touch.gemspec",
    "good_touch.sqlite3",
    "lib/good_touch.rb",
    "test/database.yml",
    "test/helper.rb",
    "test/test_good_touch.rb"
  ]
  s.homepage = %q{http://github.com/wireframe/good_touch}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{Rails 'touch' method without all the overhead}
  s.test_files = [
    "test/helper.rb",
    "test/test_good_touch.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 2.1.0"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, [">= 2.1.0"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 2.1.0"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

